# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P1_Ejemplo.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(643, 600)
        MainWindow.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_cent = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_cent.setGeometry(QtCore.QRect(360, 60, 191, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.txt_cent.setFont(font)
        self.txt_cent.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_cent.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_cent.setObjectName("txt_cent")
        self.txt_fahr = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_fahr.setGeometry(QtCore.QRect(360, 330, 191, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.txt_fahr.setFont(font)
        self.txt_fahr.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_fahr.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_fahr.setObjectName("txt_fahr")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 90, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 350, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_fahr = QtWidgets.QPushButton(self.centralwidget)
        self.btn_fahr.setGeometry(QtCore.QRect(220, 210, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_fahr.setFont(font)
        self.btn_fahr.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.btn_fahr.setObjectName("btn_fahr")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 643, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Centigrados:"))
        self.label_2.setText(_translate("MainWindow", "Fahrenheit:"))
        self.btn_fahr.setText(_translate("MainWindow", "Convertir"))
