# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P2_EvaluarOpArit.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(643, 545)
        MainWindow.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_exp = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_exp.setGeometry(QtCore.QRect(230, 40, 361, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.txt_exp.setFont(font)
        self.txt_exp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_exp.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_exp.setObjectName("txt_exp")
        self.txt_prom = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_prom.setGeometry(QtCore.QRect(230, 330, 361, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.txt_prom.setFont(font)
        self.txt_prom.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_prom.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_prom.setObjectName("txt_prom")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 60, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 350, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_exp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exp.setGeometry(QtCore.QRect(220, 210, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_exp.setFont(font)
        self.btn_exp.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.btn_exp.setObjectName("btn_exp")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 643, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Expresion:"))
        self.label_2.setText(_translate("MainWindow", "Promedio:"))
        self.btn_exp.setText(_translate("MainWindow", "Convertir"))
